"""empty message

Revision ID: 497574e85b2d
Revises: 90375a48791f
Create Date: 2020-05-14 17:25:31.874157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497574e85b2d'
down_revision = '90375a48791f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.Date(), nullable=False))
    op.drop_column('shows', 'startDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
