"""empty message

Revision ID: 90375a48791f
Revises: c241dd78a107
Create Date: 2020-05-14 14:48:29.518330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90375a48791f'
down_revision = 'c241dd78a107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###
