"""empty message

Revision ID: cc3255c4f5f2
Revises: 497574e85b2d
Create Date: 2020-05-14 20:49:53.308596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3255c4f5f2'
down_revision = '497574e85b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
